// Code generated by protoc-gen-go.
// source: test.proto
// DO NOT EDIT!

/*
Package test is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	SearchRequest
*/
package test

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type SearchRequest struct {
	Query            *string `protobuf:"bytes,1,req,name=query" json:"query,omitempty"`
	PageNumber       *int32  `protobuf:"varint,2,opt,name=page_number" json:"page_number,omitempty"`
	ResultPerPage    *int32  `protobuf:"varint,3,opt,name=result_per_page" json:"result_per_page,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}

func (m *SearchRequest) GetQuery() string {
	if m != nil && m.Query != nil {
		return *m.Query
	}
	return ""
}

func (m *SearchRequest) GetPageNumber() int32 {
	if m != nil && m.PageNumber != nil {
		return *m.PageNumber
	}
	return 0
}

func (m *SearchRequest) GetResultPerPage() int32 {
	if m != nil && m.ResultPerPage != nil {
		return *m.ResultPerPage
	}
	return 0
}

func init() {
}
